version: "3"
services:
  mysql:
    image: bitnami/mariadb:latest
    container_name: db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=autosnaps
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
    ports:
      - 3306:3306
  laravel-app:
    container_name: app
    tty: true
    image: "bitnami/laravel:latest"
    user: root
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=autosnaps
      - DB_USERNAME=test
      - DB_PASSWORD=test
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/app
